/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { AppContract } from "./App";
import { MigrationsContract } from "./Migrations";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "App"): AppContract;
      require(name: "Migrations"): MigrationsContract;
    }
  }
}

export { AppContract, AppInstance } from "./App";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
