import { LoadingButton } from "@mui/lab";
import { Button, styled, TextField } from "@mui/material";

export const LoadingMetamaskButton = styled(LoadingButton)({
  borderColor: "#333",
  borderWidth: "2px",
  background: "#00fa9a",
  color: "#333",
  fontWeight: 700,
  fontSize: "1rem",
  transition: "all .2s",
  "&:hover": {
    borderColor: "#333",
    background: "#00fa9a",
    color: "#333",
    fontWeight: 700,
    fontSize: "1rem",
    borderWidth: "2px",

    filter: "brightness(0.8)",
  },
  "&:active": {
    borderColor: "#333",
    background: "#00fa9a",
    borderWidth: "2px",
    color: "#333",
    fontWeight: 700,
    fontSize: "1rem",
    filter: "brightness(0.8)",
  },
  "&:focus": {
    borderColor: "#333",
    background: "#00fa9a",
    borderWidth: "2px",
    color: "#333",
    fontWeight: 700,
    fontSize: "1rem",
    filter: "brightness(0.8)",
  },
});
export const ButtonMetamask = styled(Button)({
  borderColor: "#333",
  borderWidth: "2px",
  background: "#00fa9a",
  color: "#333",
  fontWeight: 700,
  fontSize: "1rem",
  transition: "all .2s",
  "&:hover": {
    borderColor: "#333",
    background: "#00fa9a",
    color: "#333",
    fontWeight: 700,
    fontSize: "1rem",
    borderWidth: "2px",

    filter: "brightness(0.8)",
  },
  "&:active": {
    borderColor: "#333",
    background: "#00fa9a",
    borderWidth: "2px",
    color: "#333",
    fontWeight: 700,
    fontSize: "1rem",
    filter: "brightness(0.8)",
  },
  "&:focus": {
    borderColor: "#333",
    background: "#00fa9a",
    borderWidth: "2px",
    color: "#333",
    fontWeight: 700,
    fontSize: "1rem",
    filter: "brightness(0.8)",
  },
});
export const TextFieldMetamask = styled(TextField)({
  borderColor: "#333",
  borderWidth: "2px",
  background: "#94ffd6",
  color: "#333",
  fontWeight: 700,
  fontSize: "1rem",
  transition: "all .2s",
  "&:hover": {
    borderColor: "#333",
    background: "#94ffd6",
    color: "#333",
    fontWeight: 700,
    fontSize: "1rem",
    borderWidth: "2px",

    filter: "brightness(1.05)",
  },
  "&:active": {
    borderColor: "#333",
    background: "#94ffd6",
    borderWidth: "2px",
    color: "#333",
    fontWeight: 700,
    fontSize: "1rem",
    filter: "brightness(1.05)",
  },
  "&:focus": {
    borderColor: "#333",
    background: "#94ffd6",
    borderWidth: "2px",
    color: "#333",
    fontWeight: 700,
    fontSize: "1rem",
    filter: "brightness(1.05)",
  },
});
